export const AUTH_ACTION_TYPES = {
    SET_USER: "SET_USER",
    FETCH_USER_START: "FETCH_USER_START",
    FETCH_USER_SUCCESS: "FETCH_USER_SUCCESS",
    FETCH_USER_FAILED: "FETCH_USER_FAILED",
    SET_IS_AUTHENTICATED: "SET_IS_AUTHENTICATED",
    LOGOUT: "LOGOUT",
}